-- 코드를 입력하세요
SELECT
P.PRODUCT_ID,
P.PRODUCT_NAME,
SUM(P.PRICE * F.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER F ON P.PRODUCT_ID = F.PRODUCT_ID
WHERE PRODUCE_DATE LIKE "2022-05%"
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID