-- 코드를 작성해주세요
SELECT
    EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
    MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA
JOIN (
    SELECT
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE)
    ) AS YEARLY_MAX
ON EXTRACT(YEAR FROM DIFFERENTIATION_DATE) = YEARLY_MAX.YEAR
ORDER BY YEAR, YEAR_DEV;