-- 코드를 작성해주세요
SELECT
    F.ID,
    N.FISH_NAME,
    F.LENGTH
FROM
    FISH_INFO F
JOIN
    FISH_NAME_INFO N ON F.FISH_TYPE = N.FISH_TYPE
# WHERE 에서 LENGTH 를 타입 내에서 가장 큰 것으로 받아와야함
WHERE F.LENGTH > 10 
AND F.LENGTH = (
    SELECT MAX(F2.LENGTH)
    FROM FISH_INFO F2
    WHERE F2.FISH_TYPE = F.FISH_TYPE
    AND F2.LENGTH > 10
)
ORDER BY
    F.ID;
